# -*- coding: utf-8 -*-
"""GAIA_MED.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NEmcr4Nm50FSxpb6ljWlhcR6wMYBTCK

# Small prototype

## Setup: imports
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import folium
import geopandas as gpd, folium, json
from shapely.geometry import shape
import branca.colormap as cm
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier

"""# Load mini-ROI data"""

from google.colab import drive
drive.mount('/content/drive')

# Adjust the path if needed
file_path = "/content/drive/MyDrive/GAIAMED/gaia_med_features.csv"
df = pd.read_csv(file_path)
df.head()

"""# Tidy & parse dates"""

df = df[['month','ndvi_mean','precip_mean']]
df['month'] = pd.to_datetime(df['month'])

# Quick check for missing values
print(df.isna().sum())

"""# Build simple stress signal"""

# z-score anomalies
df['ndvi_anom'] = (df['ndvi_mean'] - df['ndvi_mean'].mean()) / df['ndvi_mean'].std()
df['precip_anom'] = (df['precip_mean'] - df['precip_mean'].mean()) / df['precip_mean'].std()

# Simple stress rule: low NDVI & low rain
df['stress'] = ((df['ndvi_anom'] < -0.5) & (df['precip_anom'] < -0.5)).astype(int)
df.head()

"""# Quick time-series view"""

plt.figure(figsize=(10,4))
plt.plot(df['month'], df['ndvi_mean'], label='NDVI')
plt.plot(df['month'], df['precip_mean']*10, label='Precip (×10)')
plt.scatter(df['month'], df['stress'], color='red', label='Stress flag')
plt.legend(); plt.grid(); plt.show()

"""# Tiny baseline model"""

# Build lagged features (previous-month values)
df['ndvi_prev'] = df['ndvi_mean'].shift(1)
df['precip_prev'] = df['precip_mean'].shift(1)
df = df.dropna()

X = df[['ndvi_mean','precip_mean','ndvi_prev','precip_prev']]
y = df['stress']

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)
print("Feature importance:", model.feature_importances_)

"""# Prototype map (single marker)"""

m = folium.Map(location=[36.7, -4.4], zoom_start=8)  # Malaga area

# Average stress color
avg_stress = df['stress'].mean()
color = 'green' if avg_stress < 0.3 else 'orange' if avg_stress < 0.6 else 'red'

popup = f"Avg NDVI: {df['ndvi_mean'].mean():.3f}<br>Avg Rain: {df['precip_mean'].mean():.3f} m<br>Stress Index: {avg_stress:.2f}"
folium.CircleMarker([36.7, -4.4], radius=20, color=color, fill=True,
                    fill_opacity=0.7, popup=popup).add_to(m)

m.save("gaia_med_map.html")
m

"""# Scaling up

# Regional setup & load
"""

import pandas as pd, numpy as np, matplotlib.pyplot as plt, folium, geopandas as gpd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler

# Mount Drive
from google.colab import drive
drive.mount('/content/drive')

# Load CSV exported from GEE
df = pd.read_csv('/content/drive/MyDrive/GAIAMED/GaiaMed_v2_full_10km_2023_2025.csv')
df.head()

"""# Clean & derive temperature"""

import json

# Extract centroid lat/lon from the .geo polygon column
def extract_centroid(geo_str):
    try:
        geo = json.loads(geo_str)
        coords = geo['coordinates'][0]  # outer ring
        lons = [c[0] for c in coords]
        lats = [c[1] for c in coords]
        return pd.Series({'lon': np.mean(lons), 'lat': np.mean(lats)})
    except:
        return pd.Series({'lon': np.nan, 'lat': np.nan})

df[['lon','lat']] = df['.geo'].apply(extract_centroid)

# Keep relevant columns (no pre-existing lat/lon needed)
df = df[['cell_id','lat','lon','month','NDVI','LST_c','temperature_2m','precip_mm','soil_moisture']]
df['month'] = pd.to_datetime(df['month'])

# Use LST_c where available, fall back to ERA5 temperature
df['temp_c'] = np.where(df['LST_c'].notna(), df['LST_c'], df['temperature_2m'] - 273.15)

# Fill missing soil_moisture with per-cell mean before z-scoring
df['soil_moisture'] = df.groupby('cell_id')['soil_moisture'].transform(lambda x: x.fillna(x.mean()))

# Drop rows still missing critical columns
df = df.dropna(subset=['temp_c'])

print(df.info())

"""# Per-cell anomalies"""

def zscore(x): return (x - x.mean()) / (x.std() + 1e-9)

df['ndvi_anom'] = df.groupby('cell_id')['NDVI'].transform(zscore)
df['rain_anom'] = df.groupby('cell_id')['precip_mm'].transform(zscore)
df['temp_anom'] = df.groupby('cell_id')['temp_c'].transform(zscore)
df['lst_anom']  = df.groupby('cell_id')['LST_c'].transform(zscore)
df['soil_anom'] = df.groupby('cell_id')['soil_moisture'].transform(zscore)

# Add season so the model knows what time of year it is
df['month_of_year'] = df['month'].dt.month
df['is_summer'] = df['month_of_year'].isin([6, 7, 8]).astype(int)
df['is_spring'] = df['month_of_year'].isin([3, 4, 5]).astype(int)
df['is_autumn'] = df['month_of_year'].isin([9, 10, 11]).astype(int)
# winter is the baseline (all three = 0)

"""# Regional stress rule"""

# Score-based: each condition = 1 point, stressed if score >= 2 out of 4
df['stress_score'] = (
    (df['ndvi_anom'] < -0.5).astype(int) +
    (df['rain_anom'] < -0.5).astype(int) +
    (df['temp_anom'] > 0.5).astype(int) +
    (df['soil_anom'] < -0.5).astype(int)
)
df['stress'] = (df['stress_score'] >= 2).astype(int)

print("Stress distribution:")
print(df['stress'].value_counts())
print(f"Stress rate: {df['stress'].mean():.3f}")

"""## Coordination linked to place names"""

from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import time

geolocator = Nominatim(user_agent="gaiamed_esade", timeout=10)
reverse = RateLimiter(geolocator.reverse, min_delay_seconds=0.5)  # 0.5s instead of 1s

def get_place(row):
    try:
        location = reverse(f"{row['lat']}, {row['lon']}", language='en')
        addr = location.raw['address']
        return addr.get('municipality') or addr.get('county') or addr.get('state', 'Unknown')
    except:
        return 'Unknown'

cell_coords = df[['cell_id','lat','lon']].drop_duplicates('cell_id').reset_index(drop=True)
total = len(cell_coords)

# Progress tracker so you know it's not frozen
results = []
for i, row in cell_coords.iterrows():
    results.append(get_place(row))
    if i % 50 == 0:
        print(f"  Progress: {i}/{total} cells done...")

cell_coords['place_name'] = results
cell_coords[['cell_id','place_name']].to_csv('cell_place_names.csv', index=False)
print(f"✅ Done! Saved {total} cells.")
print(cell_coords[['cell_id','lat','lon','place_name']].head(10))

"""# Next-month target"""

df = df.sort_values(['cell_id', 'month'])

lag_cols = ['NDVI','precip_mm','temp_c','soil_moisture',
            'ndvi_anom','rain_anom','temp_anom','soil_anom']
for col in lag_cols:
    df[f'{col}_prev'] = df.groupby('cell_id')[col].shift(1)

# Predict 2 months ahead
df['stress_next'] = df.groupby('cell_id')['stress'].shift(-2)
df = df.dropna(subset=['stress_next'] + [f'{c}_prev' for c in lag_cols])
df['stress_next'] = df['stress_next'].astype(int)

print(f"Dataset shape: {df.shape}")
print(f"Stress next distribution:\n{df['stress_next'].value_counts()}")

"""# Train/test split (time-aware) + model"""

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_auc_score

features = [
    # Current month
    'NDVI', 'precip_mm', 'temp_c', 'soil_moisture',
    'ndvi_anom', 'rain_anom', 'temp_anom', 'soil_anom', 'lst_anom',
    # Previous month
    'NDVI_prev', 'precip_mm_prev', 'temp_c_prev', 'soil_moisture_prev',
    'ndvi_anom_prev', 'rain_anom_prev', 'temp_anom_prev', 'soil_anom_prev',
    # Season
    'month_of_year', 'is_summer', 'is_spring', 'is_autumn'
]

df['month_num'] = df['month'].rank(method='dense').astype(int)
max_month = df['month_num'].max()
train_df = df[df['month_num'] <= max_month - 3]
test_df  = df[df['month_num'] >  max_month - 3]

X_train, y_train = train_df[features], train_df['stress_next']
X_test,  y_test  = test_df[features],  test_df['stress_next']

model = RandomForestClassifier(n_estimators=300, random_state=42,
                               class_weight='balanced', n_jobs=-1)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print(f"Test Accuracy: {accuracy_score(y_test, y_pred):.3f}")
print(f"Test ROC-AUC:  {roc_auc_score(y_test, y_prob):.3f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

"""# Predict latest month"""

latest = df[df['month'] == df['month'].max()].copy()
latest['stress_prob'] = model.predict_proba(latest[features])[:, 1]

def traffic_light(prob):
    if prob < 0.35:   return '🟢 Low risk'
    elif prob < 0.65: return '🟡 Moderate risk'
    else:             return '🔴 High risk'

latest['risk_level'] = latest['stress_prob'].apply(traffic_light)

# Merge place names HERE, after latest exists
place_lookup = pd.read_csv('cell_place_names.csv')
latest = latest.merge(place_lookup, on='cell_id', how='left')

print(f"Predicting stress risk for 2 months after: {df['month'].max().strftime('%Y-%m')}")
print(f"\nZone summary:")
print(latest['risk_level'].value_counts().to_string())
print(f"\nTop at-risk zones:")
print(latest[['place_name','stress_prob','risk_level']].sort_values('stress_prob', ascending=False).head(10))

"""# Choropleth map (regional)"""

import geopandas as gpd, folium, json
import numpy as np
from shapely.geometry import shape
import branca.colormap as cm

# Build grid from .geo column
raw = pd.read_csv('/content/drive/MyDrive/GAIAMED/GaiaMed_v2_full_10km_2023_2025.csv')
raw['geometry'] = raw['.geo'].apply(lambda g: shape(json.loads(g)))
grid = gpd.GeoDataFrame(raw[['cell_id','geometry']].drop_duplicates('cell_id'), crs='EPSG:4326')

latest_map = grid.merge(latest[['cell_id','stress_prob','risk_level']], on='cell_id', how='left').fillna(0)

m = folium.Map(location=[37.0, -3.5], zoom_start=7, tiles="cartodbpositron")

cmap = cm.LinearColormap(colors=['#2ECC71','#F1C40F','#E67E22','#E74C3C'],
                         vmin=0, vmax=1).to_step(10)
cmap.caption = 'Predicted Vegetation Stress Risk (2 months ahead)'

folium.GeoJson(
    latest_map.to_json(),
    name="stress",
    style_function=lambda f: {
        "fillColor": cmap(f["properties"]["stress_prob"]),
        "color": None,
        "weight": 0,
        "fillOpacity": 0.7,
    },
    tooltip=folium.GeoJsonTooltip(
        fields=["cell_id", "stress_prob", "risk_level"],
        aliases=["Zone", "Stress probability", "Risk level"],
        localize=True,
        sticky=False,
        labels=True,
        style=("background-color: white; color: #333; font-family: arial; "
               "font-size: 12px; padding: 6px; border-radius: 3px;")
    ),
).add_to(m)

cmap.add_to(m)
folium.LayerControl().add_to(m)
m.save("gaia_andalusia_map_choropleth.html")
m

"""# Time evolution (test months)"""

from sklearn.metrics import roc_auc_score

# 1) predicted probabilities for test months only
test_df = test_df.copy()
test_df['pred_prob'] = model.predict_proba(test_df[features])[:,1]

# 2) aggregate by month
obs_curve  = test_df.groupby('month')['stress_next'].mean()      # observed stressed fraction
pred_curve = test_df.groupby('month')['pred_prob'].mean()        # mean predicted stress prob
months_ix  = sorted(list(set(test_df['month'])))
print("Test months:", [m.strftime('%Y-%m') for m in months_ix])

# 3) plot
plt.figure(figsize=(9,4))
plt.plot(obs_curve.index,  obs_curve.values,  marker='o', label='Observed stressed fraction')
plt.plot(pred_curve.index, pred_curve.values, marker='s', label='Predicted stress probability (mean)')
plt.ylabel('Fraction / Probability')
plt.title('Vegetation Stress — Time Evolution (Test Months)')
plt.grid(alpha=0.3)
plt.legend()
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Optional: global test AUC as a sanity metric
auc = roc_auc_score(test_df['stress_next'], test_df['pred_prob'])
print(f"Test ROC-AUC: {auc:.3f}")

"""# Probability distribution"""

import seaborn as sns

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Left: probability distribution
sns.histplot(latest['stress_prob'], bins=30, kde=True, color='seagreen', ax=axes[0])
axes[0].axvline(0.35, color='orange', linestyle='--', label='Moderate threshold')
axes[0].axvline(0.65, color='red', linestyle='--', label='High threshold')
axes[0].set_title('Predicted Stress Probability Distribution')
axes[0].set_xlabel('Stress Probability (2 months ahead)')
axes[0].set_ylabel('Number of grid cells')
axes[0].legend()
axes[0].grid(True, alpha=0.3)

# Right: traffic light bar chart
risk_counts = latest['risk_level'].value_counts()
colors = {'🟢 Low risk': '#2ECC71', '🟡 Moderate risk': '#F1C40F', '🔴 High risk': '#E74C3C'}
bar_colors = [colors.get(k, 'grey') for k in risk_counts.index]
axes[1].bar(risk_counts.index, risk_counts.values, color=bar_colors, edgecolor='white')
axes[1].set_title('Risk Level Summary — Farmer View')
axes[1].set_ylabel('Number of zones')
axes[1].grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.show()